/*
 * A-maze-ing API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Information related to a Maze.
 */
@ApiModel(description = "Information related to a Maze.")
public class MazeInfo {
  @SerializedName("name")
  private String name = null;

  @SerializedName("totalTiles")
  private Integer totalTiles = null;

  @SerializedName("potentialReward")
  private Integer potentialReward = null;

  public MazeInfo name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The name of the maze. Might give you a hint regarding its structure.
   * @return name
  **/
  @ApiModelProperty(value = "The name of the maze. Might give you a hint regarding its structure.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public MazeInfo totalTiles(Integer totalTiles) {
    this.totalTiles = totalTiles;
    return this;
  }

   /**
   * How many tiles exist in this maze.
   * @return totalTiles
  **/
  @ApiModelProperty(value = "How many tiles exist in this maze.")
  public Integer getTotalTiles() {
    return totalTiles;
  }

  public void setTotalTiles(Integer totalTiles) {
    this.totalTiles = totalTiles;
  }

  public MazeInfo potentialReward(Integer potentialReward) {
    this.potentialReward = potentialReward;
    return this;
  }

   /**
   * The total available reward in this maze.
   * @return potentialReward
  **/
  @ApiModelProperty(value = "The total available reward in this maze.")
  public Integer getPotentialReward() {
    return potentialReward;
  }

  public void setPotentialReward(Integer potentialReward) {
    this.potentialReward = potentialReward;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MazeInfo mazeInfo = (MazeInfo) o;
    return Objects.equals(this.name, mazeInfo.name) &&
        Objects.equals(this.totalTiles, mazeInfo.totalTiles) &&
        Objects.equals(this.potentialReward, mazeInfo.potentialReward);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, totalTiles, potentialReward);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MazeInfo {\n");

    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    totalTiles: ").append(toIndentedString(totalTiles)).append("\n");
    sb.append("    potentialReward: ").append(toIndentedString(potentialReward)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

